# See http://docs.travis-ci.com/user/customizing-the-build/
# See ./travis/* for the actual scripts that get run

os:
    - linux
    - osx
language: cpp
sudo: required

env:
  - THENEEDFORTHIS=FAIL

branches:
  except:
    - debian
    - nightly/debian
    - nightly/ubuntu
    - ubuntu

matrix:
  include:
    - env: QTTYPE=4
#    - env: QTTYPE=5
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x ./travis/before_install.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/before_install_osx.sh

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x ./travis/install.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/install_osx.sh

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x ./travis/before_script.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/before_script_osx.sh

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x ./travis/script.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/script_osx.sh

notifications: 
  irc: 
    channels: 
      - "chat.freenode.net#huggle"
    on_failure: always
    on_success: change
